### ISSUE TITLE
Incompatible with GoLand 2022.3

### ISSUE THREAD

**Issue by lachis** [frykher/jetbrains-kanagawa-theme#1]
Hi @frykher, 

Love the work you have done on this so far. Would it be possible to have this plugin updated for GoLand 2022.3? 
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/5248669/205060103-eb0ecc6a-16e9-44c8-9000-161f579353d4.png">

I would submit an MR to help out but never worked with jetbrains plugins.

Thanks!

**Comment by frykher** [comment]
Thanks for letting me know. I'll update the plugin asap

**Comment by frykher** [comment]
Super sorry for the long wait, I've just submitted the plugin to JetBrains for approval but in the meantime you can grab the plugin jar from the releases page on GitHub. I'll close this issue once the plugin is approved.

**Comment by lachis** [comment]
thanks a lot @frykher
