### ISSUE TITLE
Please update it to 2022.3

### ISSUE THREAD

**Issue by Lamarcke** [frykher/jetbrains-kanagawa-theme#2]
This plugin is really cool, thank you for your work.
Please update it to the 2022.3 version.

There's a bug that allows me to install incompatible versions, and your plugin works fine even in the new UI.
However, i need to disable and enable it everytime i re-open my IDE...

**Comment by Lamarcke** [comment]
@frykher 
Sorry for tagging you.
I've a [fork ](https://github.com/Lamarcke/jetbrains-kanagawa-theme) with a changed `build.gradle.kts` file which works fine on 2022.3.

Keep in mind I've also removed some stuff related to uploading the theme, so i believe you only should only keep this line:
```
// Configure Gradle IntelliJ Plugin - read more: https://github.com/JetBrains/gradle-intellij-plugin
intellij {
	version.set("2022.2")
	updateSinceUntilBuild.set(false)
}

tasks.patchPluginXml {
	sinceBuild.set("222")
}
```

I've tested it with the new UI and it works fine, i believe you may want to do further testing, but this removes the "outdated" error on the plugins UI. 

Your publish.yml workflow was a huge help. Thank you. I almost went back to 2022.2.4 just for this theme, nice work! :)

**Comment by Lamarcke** [comment]
No worries, i'm glad it worked out!
By the way, i couldn't really tell you exactly what it does, since i just cross-referenced them from a plugin that was working with 2022.3 (Everything to avoid going in the cryptic jetbrains docs) lol 

I also noticed that this said plugin had no "max" version set, meaning it wouldn't need to be manually updated to be usable in newer versions. So, just my guess:
```
tasks.patchPluginXml {
	sinceBuild.set("222")
}
```
without the `untilBuild.set("222.*")` removes this "max" version. It's just my guess, though.

Thank you for the update. 
Is there any way i can contribute to further improve it? I believe i would need to mess with the files in `src/main/resources`, right?

**Comment by frykher** [comment]
Yeah the theme and the editor color scheme is stored there. I would say the color scheme is pretty much complete but the UI theme is kind of rough. A good place to start might be the active buttons because the contrast between the green and the text color is pretty bad. Choosing wave Aqua as an accent color in the first place was a blunder. You can find a color to replace it with in the original Kanagawa theme README: https://github.com/rebelot/kanagawa.nvim
